@startuml
Consenter -> "Consent Server System": Retrieve a previously filed consent
"Consent Server System" --> Consenter: Return previous consent record
Consenter -> "Consent Server System": Request a record of activities authorized or blocked
"Consent Server System" --> Consenter: Return list of activities based on chosen consent
@enduml
