@startuml
"Consent Server System A" -> "Consent Server System B": Subscribe to receive consent events
loop 
   "Consent Server System B" -> "Consent Server System A": Send consent event
end 
"Consent Server System A" -> "Consent Server System B": End subscription to consent events
@enduml
