@startuml
"Consent Server System" -> Consenter: Send the rendered consent form
loop
    Consenter -> Consenter: Reviews the consent form 
    Consenter -> "Consent Server System": Saves partially filled form
end
@enduml
